development:
  adapter: postgresql
  encoding: unicode
  database: gschool_development
  host: localhost
  port: 5432
  pool: 5
  username: gschool
  password: gschool

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: gschool_test
  pool: 5
  username: gschool
  password: gschool
